spring.application.name=ProyectoSpring_BackendJaMaJo

# Puede que haya que cambiar la URL
spring.datasource.url=jdbc:mysql://localhost:3306/JAMAJO_DDBB
spring.datasource.username=root
spring.datasource.password=AlumnoIFP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect